name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true 
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: echo "The Environment is ${{inputs.environment}}"
      - run: echo "The value of the Environment-Variable DESCRIPTION is ${{vars.DESCRIPTION}}"
      - run: echo "My User-Secret is ${{ secrets.MONGODB-USERNAME }}"
